AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Application Template for AWS SAM

Globals:
  Function:
    Timeout: 5
    Runtime: go1.x
    Architectures:
      - x86_64

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

  LogLevel:
    Type: String
    Description: Log level
    Default: DEBUG
    AllowedValues:
      - DEBUG
      - INFO

Resources:
  MonolithFinitoAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FinitoTransactions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

#  GetTransactionFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName:
#      CodeUri: ./bin/
#      Handler: getTransaction
#      Events:
#        GetTransaction:
#          Type: Api
#          Properties:
#            Path: /transactions/{id}
#            Method: get
#            RestApiId: !Ref MonolithFinitoAPI
#      Environment:
#        Variables:
#          TABLE_NAME: !Ref TransactionsTable
#      Policies:
#        - DynamoDBReadPolicy:
#            TableName: !Ref TransactionsTable

  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "greetings"
      CodeUri: ./cmd/functions/hello
      Handler: hello
      Events:
        Greeting:
          Type: Api
          Properties:
            RestApiId: !Ref MonolithFinitoAPI
            Path: /greeting
            Method: GET
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel